makeFILE:are used to help decide which parts of a large program need to be recompiled. 
用makefile的好处
1. a generalized file。 可以用于很多种programming language
2. efficient.如果有的文件没改，就不需要re-compile.

++i is faster than i++ -> ++i pre-increment operator, which increments the value of 'i' immediately and returns the incremented value. 
->“i++” is known as the post-increment operator, which increments the value of 'i' but returns the original value that 'i' held before being incremented.

“Object File”: Contains the compiled contents of the corresponding .c或者.h program -> .o contain the computer-language verison.

.c / .h file -> intermediatefile (c preprocessor) -> compiler (.s) -> assembler (.o) -> to link with library -> generated executable files.


单引号->character
双引号-> string

C-c C-v: run makefile in emacs
C-x b:切换窗口








 
